// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenTimesheets.Server;

namespace OpenTimesheets.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OpenTimesheets.Shared.Entities.ProjAlloc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Activity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Hrs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProjCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkShiftFk")
                        .HasColumnType("int");

                    b.Property<int?>("WorkShiftId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkShiftId");

                    b.ToTable("ProjAlloc");
                });

            modelBuilder.Entity("OpenTimesheets.Shared.Entities.WorkShift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("HrsBreak")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HrsElapsed")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HrsNorm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ShiftDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ShiftEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ShiftStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserFk")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkShifts");
                });

            modelBuilder.Entity("OpenTimesheets.Shared.Entities.ProjAlloc", b =>
                {
                    b.HasOne("OpenTimesheets.Shared.Entities.WorkShift", null)
                        .WithMany("ProjAllocs")
                        .HasForeignKey("WorkShiftId");
                });

            modelBuilder.Entity("OpenTimesheets.Shared.Entities.WorkShift", b =>
                {
                    b.Navigation("ProjAllocs");
                });
#pragma warning restore 612, 618
        }
    }
}
